version: 2

run:
  timeout: 5m
  go: '1.24'
  tests: true
  skip-dirs:
    - vendor
    - tmp
    - bin

linters:
  enable:
    # Enabled by default
    - errcheck      # Check for unchecked errors
    - govet         # Standard Go vet checks
    - ineffassign   # Detect ineffectual assignments
    - staticcheck   # Advanced static analysis (includes gosimple)
    - unused        # Check for unused code

    # Additional valuable linters
    - misspell      # Find misspelled words
    - unconvert     # Remove unnecessary conversions
    - gocritic      # Comprehensive checks
    - bodyclose     # Check HTTP response body close
    - errname       # Check error naming conventions
    - errorlint     # Find code with error wrapping issues
    - copyloopvar   # Check for loop variable capture (replaces exportloopref)
    - nilerr        # Find code returning nil with non-nil error
    - nilnil        # Find code returning nil with nil error
    - predeclared   # Find code shadowing predeclared identifiers
    - reassign      # Check for reassigning to variables
    - usestdlibvars # Suggest using stdlib constants
    ## TODO(jjo) -> fix for below linters
    #- unparam       # Find unused function parameters
    #- revive        # Fast, configurable linter
    #- gosec         # Security checks
    #- noctx         # Find HTTP requests without context
    #- prealloc      # Find slice declarations that could be preallocated

  disable:
    # Opinionated style linters that may conflict with project style
    - varnamelen    # Too strict on variable names
    - exhaustruct   # Requires all struct fields - too strict
    - nlreturn      # Requires newlines - too opinionated
    - wsl           # Whitespace linter - too opinionated
    - gochecknoglobals # Globals are used intentionally in this project
    - mnd           # Magic number detector - superseded by gocritic

formatters:
  enable:
    - gofmt         # Check formatting
    - gofumpt       # Stricter gofmt
    - goimports     # Check import formatting

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
    exclude-functions:
      - (*os.File).Close
      - (*database/sql.Rows).Close

  govet:
    enable-all: true
    settings:
      shadow:
        strict: true

  gofmt:
    simplify: true

  goimports:
    local-prefixes: github.com/jjo/promql-cli

  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
      - experimental
    disabled-checks:
      - whyNoLint  # We don't require explanation for nolint directives
      - hugeParam  # Can be overly strict

  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: increment-decrement
      - name: var-naming
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unused-parameter
      - name: unreachable-code
      - name: redefines-builtin-id

  staticcheck:
    checks: ["all"]

  gosec:
    excludes:
      - G104  # Audit errors not checked - covered by errcheck
      - G204  # Subprocess with variable - needed for external editor
      - G304  # File path from variable - needed for file operations
      - G306  # Write file permissions - test files use appropriate perms
    config:
      global:
        audit: true

  misspell:
    locale: US
    ignore-words:
      - promql
      - prometheus
      - grafana
      - tsdb

  errorlint:
    errorf: true
    asserts: true
    comparison: true

issues:
  # Don't hide issues by default
  exclude-use-default: false

  # Maximum issues count per one linter
  max-issues-per-linter: 0

  # Maximum count of issues with the same text
  max-same-issues: 0

  # Exclude specific issues
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gosec
        - errcheck
        - gocritic

    # Exclude tool generation files
    - path: tools/genmodels/
      linters:
        - errcheck
        - gosec

    # Allow context.Background in main and test files
    - path: (cmd/promql-cli/main\.go|_test\.go)
      text: "context.Background"
      linters:
        - contextcheck

    # Ignore long functions in REPL (complex interactive logic)
    - path: pkg/repl/(repl\.go|prompt_repl\.go)
      text: "Function .* is too long"
      linters:
        - gocritic

    # Allow defer in loops for scoped cleanup (intentional pattern)
    - text: "deferInLoop:"
      linters:
        - gocritic

    # Ignore complexity in parser functions
    - path: pkg/storage/simple_tsdb\.go
      linters:
        - gocyclo
        - cyclop
        - gocognit

  # Show all issues from a linter
  new: false

  # Fix found issues (if supported by linter)
  fix: false

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
