// Code generated by tools/genmodels at 2025-09-22T20:17:53Z; DO NOT EDIT.
package ai

func init() {
	modelCatalogHolder = map[string][]ModelInfo{
		"openai": {
			{ID: "gpt-4o-mini", Display: "gpt-4o-mini", Family: "", ContextK: 0, Description: ""},
			{ID: "gpt-4o", Display: "gpt-4o", Family: "", ContextK: 0, Description: ""},
			{ID: "gpt-4.1-mini", Display: "gpt-4.1-mini", Family: "", ContextK: 0, Description: ""},
			{ID: "gpt-4.1", Display: "gpt-4.1", Family: "", ContextK: 0, Description: ""},
			{ID: "o3-mini", Display: "o3-mini", Family: "", ContextK: 0, Description: ""},
			{ID: "o4-mini", Display: "o4-mini", Family: "", ContextK: 0, Description: ""},
		},
		"grok": {
			{ID: "grok-2-1212", Display: "grok-2-1212", Family: "", ContextK: 0, Description: ""},
			{ID: "grok-2-image-1212", Display: "grok-2-image-1212", Family: "", ContextK: 0, Description: ""},
			{ID: "grok-2-vision-1212", Display: "grok-2-vision-1212", Family: "", ContextK: 0, Description: ""},
			{ID: "grok-3", Display: "grok-3", Family: "", ContextK: 0, Description: ""},
			{ID: "grok-3-mini", Display: "grok-3-mini", Family: "", ContextK: 0, Description: ""},
			{ID: "grok-4-0709", Display: "grok-4-0709", Family: "", ContextK: 0, Description: ""},
			{ID: "grok-4-fast-non-reasoning", Display: "grok-4-fast-non-reasoning", Family: "", ContextK: 0, Description: ""},
			{ID: "grok-4-fast-reasoning", Display: "grok-4-fast-reasoning", Family: "", ContextK: 0, Description: ""},
			{ID: "grok-code-fast-1", Display: "grok-code-fast-1", Family: "", ContextK: 0, Description: ""},
		},
		"claude": {
			{ID: "claude-3-5-haiku-20241022", Display: "Claude Haiku 3.5", Family: "", ContextK: 0, Description: ""},
			{ID: "claude-3-5-sonnet-20240620", Display: "Claude Sonnet 3.5 (Old)", Family: "", ContextK: 0, Description: ""},
			{ID: "claude-3-5-sonnet-20241022", Display: "Claude Sonnet 3.5 (New)", Family: "", ContextK: 0, Description: ""},
			{ID: "claude-3-7-sonnet-20250219", Display: "Claude Sonnet 3.7", Family: "", ContextK: 0, Description: ""},
			{ID: "claude-3-haiku-20240307", Display: "Claude Haiku 3", Family: "", ContextK: 0, Description: ""},
			{ID: "claude-3-opus-20240229", Display: "Claude Opus 3", Family: "", ContextK: 0, Description: ""},
			{ID: "claude-opus-4-1-20250805", Display: "Claude Opus 4.1", Family: "", ContextK: 0, Description: ""},
			{ID: "claude-opus-4-20250514", Display: "Claude Opus 4", Family: "", ContextK: 0, Description: ""},
			{ID: "claude-sonnet-4-20250514", Display: "Claude Sonnet 4", Family: "", ContextK: 0, Description: ""},
		},
		"ollama": {
			{ID: "llama3.1", Display: "Llama 3.1", Family: "", ContextK: 0, Description: ""},
			{ID: "qwen2.5", Display: "Qwen 2.5", Family: "", ContextK: 0, Description: ""},
		},
	}
}
