package main

import (
	"bytes"
	"flag"
	"fmt"
	"io"
	"strings"

	"github.com/peterbourgon/ff/v3/ffcli"
)

// Value hints for flag arguments, keyed by flag name (long and short forms).
// Value flags not listed in either map complete nothing.
var (
	completionValues = map[string][]string{
		"repl":       {"prompt", "readline"},
		"log.level":  {"debug", "info", "warn", "error"},
		"log.format": {"text", "json"},
		"format":     {"text", "tap", "junit", "json"},
		"output":     {"json"},
		"o":          {"json"},
	}
	completionFiles  = map[string]bool{"file": true, "f": true, "rules": true}
	completionShells = []string{"bash", "zsh", "fish"}
)

// cFlag is a flag as seen by the completion generators.
type cFlag struct {
	opt    string // as typed: --name, or -x for single-letter flags
	usage  string
	isBool bool
	values []string
	files  bool
}

// cScope is the root command (name "") or one subcommand.
type cScope struct {
	name      string
	help      string
	flags     []cFlag
	posValues []string // fixed positional candidates, if any
	posFiles  bool     // positional arguments are file names
}

// writeCompletion writes the completion script for shell, generated from the
// command tree rooted at root so new flags and subcommands show up automatically.
func writeCompletion(w io.Writer, shell string, root *ffcli.Command) error {
	scopes := collectScopes(root)
	var b bytes.Buffer
	switch shell {
	case "bash":
		genBash(&b, root.Name, scopes)
	case "zsh":
		genZsh(&b, root.Name, scopes)
	case "fish":
		genFish(&b, root.Name, scopes)
	default:
		return fmt.Errorf("unsupported shell %q (supported: %s)", shell, strings.Join(completionShells, ", "))
	}
	_, err := w.Write(b.Bytes())
	return err
}

func collectScopes(root *ffcli.Command) []cScope {
	scopes := []cScope{{flags: collectFlags(root.FlagSet)}}
	for _, sub := range root.Subcommands {
		sc := cScope{name: sub.Name, help: subcommandHelp(sub), flags: collectFlags(sub.FlagSet), posFiles: true}
		if sub.Name == "completion" {
			sc.posValues, sc.posFiles = completionShells, false
		}
		scopes = append(scopes, sc)
	}
	return scopes
}

// subcommandHelp returns a non-empty description: ShortHelp, else ShortUsage, else the name,
// since shells (zsh _describe in particular) mishandle entries without one.
func subcommandHelp(sub *ffcli.Command) string {
	for _, h := range []string{sub.ShortHelp, sub.ShortUsage, sub.Name} {
		if h = strings.TrimSpace(h); h != "" {
			return h
		}
	}
	return sub.Name
}

func collectFlags(fs *flag.FlagSet) []cFlag {
	var out []cFlag
	if fs == nil {
		return out
	}
	fs.VisitAll(func(f *flag.Flag) {
		opt := "--" + f.Name
		if len(f.Name) == 1 {
			opt = "-" + f.Name
		}
		bf, ok := f.Value.(interface{ IsBoolFlag() bool })
		out = append(out, cFlag{
			opt:    opt,
			usage:  f.Usage,
			isBool: ok && bf.IsBoolFlag(),
			values: completionValues[f.Name],
			files:  completionFiles[f.Name],
		})
	})
	return out
}

func funcName(prog string) string {
	return "_" + strings.NewReplacer("-", "_", ".", "_").Replace(prog)
}

func flagWords(flags []cFlag) string {
	s := make([]string, 0, len(flags))
	for _, f := range flags {
		s = append(s, f.opt)
	}
	return strings.Join(s, " ")
}

func valueFlags(flags []cFlag) []cFlag {
	var out []cFlag
	for _, f := range flags {
		if !f.isBool {
			out = append(out, f)
		}
	}
	return out
}

func genBash(b *bytes.Buffer, prog string, scopes []cScope) {
	fn := funcName(prog)
	rootValueFlags := make([]string, 0, len(scopes[0].flags))
	for _, f := range valueFlags(scopes[0].flags) {
		rootValueFlags = append(rootValueFlags, f.opt)
	}
	skipPattern := `"--"` // never matches when the root has no value flags
	if len(rootValueFlags) > 0 {
		skipPattern = strings.Join(rootValueFlags, "|")
	}

	fmt.Fprintf(b, "# bash completion for %s (generated by \"%s completion bash\")\n", prog, prog)
	fmt.Fprintf(b, `%s() {
    local cur prev cmd i w
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev=""
    if (( COMP_CWORD > 0 )); then
        prev="${COMP_WORDS[COMP_CWORD-1]}"
    fi
    # bash splits --flag=value into "--flag" "=" "value"
    if [[ $cur == "=" ]]; then
        cur=""
    elif [[ $prev == "=" ]] && (( COMP_CWORD > 1 )); then
        prev="${COMP_WORDS[COMP_CWORD-2]}"
    fi

    # Find the subcommand: first non-flag word, skipping root flag values.
    cmd=""
    for (( i = 1; i < COMP_CWORD; i++ )); do
        w="${COMP_WORDS[i]}"
        case "$w" in
            %s)
                if [[ ${COMP_WORDS[i+1]} == "=" ]]; then
                    i=$(( i + 2 ))
                else
                    i=$(( i + 1 ))
                fi
                ;;
            -*|"=") ;;
            *) cmd="$w"; break ;;
        esac
    done

    case "$cmd" in
`, fn, skipPattern)

	for _, sc := range scopes {
		if sc.name == "" {
			fmt.Fprintf(b, "        \"\")\n")
		} else {
			fmt.Fprintf(b, "        %s)\n", sc.name)
		}
		if vf := valueFlags(sc.flags); len(vf) > 0 {
			fmt.Fprintf(b, "            case \"$prev\" in\n")
			for _, f := range vf {
				switch {
				case len(f.values) > 0:
					fmt.Fprintf(b, "                %s) COMPREPLY=( $(compgen -W %q -- \"$cur\") ); return ;;\n", f.opt, strings.Join(f.values, " "))
				case f.files:
					fmt.Fprintf(b, "                %s) return ;; # file names via -o default\n", f.opt)
				default:
					fmt.Fprintf(b, "                %s) compopt +o default 2>/dev/null; return ;;\n", f.opt)
				}
			}
			fmt.Fprintf(b, "            esac\n")
		}
		if len(sc.flags) > 0 {
			fmt.Fprintf(b, "            if [[ $cur == -* ]]; then\n                COMPREPLY=( $(compgen -W %q -- \"$cur\") )\n                return\n            fi\n", flagWords(sc.flags))
		}
		switch {
		case sc.name == "":
			names := make([]string, 0, len(scopes))
			for _, o := range scopes[1:] {
				names = append(names, o.name)
			}
			fmt.Fprintf(b, "            COMPREPLY=( $(compgen -W %q -- \"$cur\") )\n", strings.Join(names, " "))
		case len(sc.posValues) > 0:
			fmt.Fprintf(b, "            COMPREPLY=( $(compgen -W %q -- \"$cur\") )\n", strings.Join(sc.posValues, " "))
		default:
			fmt.Fprintf(b, "            : # positional file names via -o default\n")
		}
		fmt.Fprintf(b, "            ;;\n")
	}
	fmt.Fprintf(b, "    esac\n}\n\ncomplete -o default -F %s %s\n", fn, prog)
}

func zshQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

func zshSpecs(flags []cFlag) []string {
	specs := make([]string, 0, len(flags))
	for _, f := range flags {
		spec := f.opt
		if !f.isBool {
			spec += "="
		}
		spec += "[" + strings.NewReplacer(`[`, `\[`, `]`, `\]`).Replace(f.usage) + "]"
		if !f.isBool {
			switch {
			case len(f.values) > 0:
				spec += ":value:(" + strings.Join(f.values, " ") + ")"
			case f.files:
				spec += ":file:_files"
			default:
				spec += ":value: "
			}
		}
		specs = append(specs, zshQuote(spec))
	}
	return specs
}

func genZsh(b *bytes.Buffer, prog string, scopes []cScope) {
	fn := funcName(prog)
	fmt.Fprintf(b, "#compdef %s\n# zsh completion for %s (generated by \"%s completion zsh\")\n\n", prog, prog, prog)
	fmt.Fprintf(b, "%s() {\n    local curcontext=\"$curcontext\" state line ret=1\n    typeset -A opt_args\n\n", fn)
	fmt.Fprintf(b, "    local -a commands\n    commands=(\n")
	for _, sc := range scopes[1:] {
		fmt.Fprintf(b, "        %s\n", zshQuote(sc.name+":"+strings.ReplaceAll(sc.help, ":", `\:`)))
	}
	fmt.Fprintf(b, "    )\n\n    _arguments -C \\\n")
	for _, s := range zshSpecs(scopes[0].flags) {
		fmt.Fprintf(b, "        %s \\\n", s)
	}
	fmt.Fprintf(b, "        '1: :->cmds' \\\n        '*::arg:->args' && ret=0\n\n")
	fmt.Fprintf(b, "    case $state in\n        cmds)\n            _describe -t commands '%s command' commands && ret=0\n            ;;\n        args)\n            case $line[1] in\n", prog)
	for _, sc := range scopes[1:] {
		fmt.Fprintf(b, "                %s)\n                    _arguments \\\n", sc.name)
		for _, s := range zshSpecs(sc.flags) {
			fmt.Fprintf(b, "                        %s \\\n", s)
		}
		switch {
		case len(sc.posValues) > 0:
			fmt.Fprintf(b, "                        '1:shell:(%s)' && ret=0\n", strings.Join(sc.posValues, " "))
		case sc.posFiles:
			fmt.Fprintf(b, "                        '1:file:_files' && ret=0\n")
		default:
			fmt.Fprintf(b, "                        '*: :' && ret=0\n")
		}
		fmt.Fprintf(b, "                    ;;\n")
	}
	fmt.Fprintf(b, "            esac\n            ;;\n    esac\n    return ret\n}\n\n")
	fmt.Fprintf(b, "if [ \"$funcstack[1]\" = %q ]; then\n    %s \"$@\"\nelse\n    compdef %s %s\nfi\n", fn, fn, fn, prog)
}

func fishQuote(s string) string {
	return "'" + strings.NewReplacer(`\`, `\\`, `'`, `\'`).Replace(s) + "'"
}

func genFish(b *bytes.Buffer, prog string, scopes []cScope) {
	fn := funcName(prog)
	rootValueFlags := make([]string, 0, len(scopes[0].flags))
	for _, f := range valueFlags(scopes[0].flags) {
		rootValueFlags = append(rootValueFlags, f.opt)
	}

	fmt.Fprintf(b, "# fish completion for %s (generated by \"%s completion fish\")\n\n", prog, prog)
	// Prints the current subcommand, skipping root flags and their values.
	fmt.Fprintf(b, `function %[1]s_subcmd
    set -l skip 0
    for t in (commandline -opc)[2..-1]
        if test $skip -eq 1
            set skip 0
            continue
        end
        if contains -- $t %[2]s
            set skip 1
            continue
        end
        if string match -q -- '-*' $t
            continue
        end
        echo $t
        return 0
    end
    return 1
end

function %[1]s_needs_subcmd
    set -l c (%[1]s_subcmd)
    test -z "$c"
end

function %[1]s_using_subcmd
    set -l c (%[1]s_subcmd)
    test "$c" = $argv[1]
end

`, fn, strings.Join(append(rootValueFlags, "--"), " "))

	for _, sc := range scopes {
		cond := fn + "_needs_subcmd"
		if sc.name != "" {
			cond = fmt.Sprintf("'%s_using_subcmd %s'", fn, sc.name)
		} else {
			for _, o := range scopes[1:] {
				line := fmt.Sprintf("complete -c %s -f -n %s -a %s", prog, cond, o.name)
				if o.help != "" {
					line += " -d " + fishQuote(o.help)
				}
				fmt.Fprintln(b, line)
			}
		}
		for _, f := range sc.flags {
			kind := "-l " + strings.TrimPrefix(f.opt, "--")
			if !strings.HasPrefix(f.opt, "--") {
				kind = "-s " + strings.TrimPrefix(f.opt, "-")
			}
			line := fmt.Sprintf("complete -c %s -n %s %s", prog, cond, kind)
			if !f.isBool {
				switch {
				case len(f.values) > 0:
					line += " -x -a " + fishQuote(strings.Join(f.values, " "))
				case f.files:
					line += " -r"
				default:
					line += " -x"
				}
			}
			fmt.Fprintf(b, "%s -d %s\n", line, fishQuote(f.usage))
		}
		switch {
		case sc.name == "":
		case len(sc.posValues) > 0:
			fmt.Fprintf(b, "complete -c %s -f -n %s -a %s\n", prog, cond, fishQuote(strings.Join(sc.posValues, " ")))
		default:
			fmt.Fprintf(b, "complete -c %s -n %s -a '(__fish_complete_path (commandline -ct))'\n", prog, cond)
		}
	}
}
